### ISSUE TITLE
Nodejs quickstarter broken with node8 - fails during npm run coverage

### ISSUE THREAD

**Issue by clemensutschig** [opendevstack/ods-project-quickstarters#22]
cleme-cd-be-node-express2-test] Running shell script
+ npm run coverage

> data@0.0.0 coverage /tmp/workspace/cleme-cd/cleme-cd-be-node-express2-test
> nyc --include="src/**/*.ts" --reporter=text --reporter=html --reporter=lcov mocha --compilers ts:ts-node/register --recursive "test/**/*-spec.ts"

/tmp/workspace/cleme-cd/cleme-cd-be-node-express2-test/node_modules/ts-node/src/index.ts:316
        throw new TypeError(
              ^
TypeError: Unable to require `.d.ts` file.
This is usually the result of a faulty configuration or import. Make sure there is a `.js`, `.json` or another executable extension and loader (attached before `ts-node`) available alongside `greeter.d.ts`.
    at getOutput (/tmp/workspace/cleme-cd/cleme-cd-be-node-express2-test/node_modules/ts-node/src/index.ts:316:15)
    at /tmp/workspace/cleme-cd/cleme-cd-be-node-express2-test/node_modules/ts-node/src/index.ts:336:16
    at Object.compile (/tmp/workspace/cleme-cd/cleme-cd-be-node-express2-test/node_modules/ts-node/src/index.ts:498:11)
    at Object.m._compile (/tmp/workspace/cleme-cd/cleme-cd-be-node-express2-test/node_modules/ts-node/src/index.ts:392:43)
    at Module._extensions..js (module.js:663:10)
    at Object.require.extensions.(anonymous function) [as .ts] (/tmp/workspace/cleme-cd/cleme-cd-be-node-express2-test/node_modules/ts-node/src/index.ts:395:12)
    at NYC._readTranspiledSource (/tmp/workspace/cleme-cd/cleme-cd-be-node-express2-test/node_modules/nyc/index.js:160:26)
    at NYC.addFile (/tmp/workspace/cleme-cd/cleme-cd-be-node-express2-test/node_modules/nyc/index.js:144:21)
    at /tmp/workspace/cleme-cd/cleme-cd-be-node-express2-test/node_modules/nyc/index.js:176:11
    at /tmp/workspace/cleme-cd/cleme-cd-be-node-express2-test/node_modules/nyc/index.js:244:5
npm ERR! code ELIFECYCLE

**Comment by clemensutschig** [comment]
steps to repro : 

- based on latest ods-project-quickstarters 
- provisioned a new nodejs project thru provisioniong app

jenkins started building based off master - and failed

**Comment by michaelsauter** [comment]
@ManuelFeller do you know why this is happening? Maybe some updated dependency?

**Comment by ManuelFeller** [comment]
After checking our theory after we talked it I could verify the reason. The coverage test checks all subdirectories, and it finds the built version in the docker subdirectory. When adding the docker directory to the exclude list it no longer has this issue. Will create a PR soon...
