### ISSUE TITLE
be-python-flask CoverageException("No data to report.") 

### ISSUE THREAD

**Issue by henrjk** [opendevstack/ods-project-quickstarters#417]
**Describe the bug**
The quickstarters jenkins build fail during the coverage state when the workspace has the name tests in it. 

**To Reproduce**

1. Deliver a change to the quickstarter with a branch name containing the word tests in it such as feature/activate-tests
2. The build fails as shown above

**Expected behavior**
build should not use the workspace directory name derived from the feature branch when omitting code. 

**Affected version (please complete the following information):**
 - Quickstarter master, 1.2.x and probably earlier

**Log Output (ensure to remove any confidential information like tokens, project names, etc.**
```
The log message is as follows(excerpt):

```
Name    Stmts   Miss Branch BrPart  Cover
-----------------------------------------
Traceback (most recent call last):
  File "/tmp/workspace/project-cd/project-cd-be-python-flask-feature-activate-tests/venv/bin/nosetests", line 8, in <module>
    sys.exit(run_exit())
...
  File "/tmp/workspace/project-cd/project-cd-be-python-flask-feature-activate-tests/venv/lib/python3.6/site-packages/coverage/summary.py", line 158, in report
    raise CoverageException("No data to report.")
coverage.misc.CoverageException: No data to report.
atexit: <coverage.control.Coverage object at 0x7f3efc615a90>
```

**Additional context**
Changing the omit setting in https://github.com/opendevstack/ods-project-quickstarters/blob/1a951048067adaf80dafd05dd32a2b81461e2723/boilerplates/be-python-flask/files/src/tests/.coveragerc#L4 to 

```
omit = *src/tests*
       *__init__*
```

fixed the issue for me. 
However I am not certain this is the right approach and would also work on Windows for example.

**Comment by michaelsauter** [comment]
@adyachok Could you please look into this issue this week or next?

**Comment by michaelsauter** [comment]
@adyachok @gerardcl Can you please look into this?
