### ISSUE TITLE
node version in deployment image doesn't match build image

### ISSUE THREAD

**Issue by tbugfinder** [opendevstack/ods-project-quickstarters#445]
**Describe the bug**
The project is built using nodejs8 however the deployment is based on nodejs6 - this is a mismatch and doesn't work.

https://github.com/opendevstack/ods-project-quickstarters/blob/master/boilerplates/be-node-express/Jenkinsfile#L25

**To Reproduce**
1. Build a project which makes use of modules.

**Expected behavior**
Built modules should be reusable within deployment.

**Screenshots**
<none>

**Affected version (please complete the following information):**
 - OpenShift: [3.11]
 - OpenDevStack [1.2.x]

**Log Output (ensure to remove any confidential information like tokens, project names, etc.**
```
Error: Missing binding /node/node_modules/node-sass/vendor/linux-x64-48/binding.node
Node Sass could not find a binding for your current environment: Linux 64-bit with Node.js 6.x

Found bindings for the following environments:
  - Linux 64-bit with Unsupported runtime (57)

This usually happens because your environment has changed since running `npm install`.
Run `npm rebuild node-sass` to build the binding for your current environment.
    at module.exports (/node/node_modules/node-sass/lib/binding.js:15:13)
    at Object.<anonymous> (/node/node_modules/node-sass/lib/index.js:14:35)
    at Module._compile (module.js:577:32)

```

**Additional context**
Very easy to fix :-)

**Comment by michaelsauter** [comment]
@ManuelFeller @cschweikert @akhilsoman @bljubisic Could one of you tackle this? Please assign yourself. As I said, ideally we get this to node 10.

**Comment by tbugfinder** [comment]
[note] Were there any thoughts on those RedHat UBIs?
https://www.redhat.com/en/blog/introducing-red-hat-universal-base-image

**Comment by michaelsauter** [comment]
@tbugfinder Thanks for the link, I was not aware of that. I opened a new issue (in the new repo for quickstarters): https://github.com/opendevstack/ods-quickstarters/issues/7.

For ODS 2, we should stick with the Alpine-based ones.

**Comment by akhilsoman** [comment]
@michaelsauter I could take a look . Can you assign it to me, I couldn't do it myself

**Comment by michaelsauter** [comment]
@akhilsoman Thank you very much, I assigned you now. I will prepare a guide how to use the new quickstarters today - you can use that then to fix this issue for ODS 2.
