### ISSUE TITLE
scala sbt quickstarter broken - file:/?/.sbt/preloaded/org/fusesource/jansi/jansi/1.4/jansi-1.4.pom. Please retry. (0ms)

### ISSUE THREAD

**Issue by clemensutschig** [opendevstack/ods-project-quickstarters#56]
Rundeck provisionioning of sbt / scala quickstarter:

problem while downloading module descriptor: file:/?/.sbt/preloaded/org/fusesource/jansi/jansi/1.4/jansi-1.4.pom: Downloaded file size doesn't match expected Content Length for file:/?/.sbt/preloaded/org/fusesource/jansi/jansi/1.4/jansi-1.4.pom. Please retry. (0ms)
--
18:55:46 |  
18:55:46 |  
18:55:46 | :: USE VERBOSE OR DEBUG MESSAGE LEVEL FOR MORE DETAILS
18:55:46 | :: retrieving :: org.scala-sbt#boot-scala
18:55:46 | confs: [default]
18:55:46 | 5 artifacts copied, 0 already retrieved (24560kB/29ms)
18:55:48 | java.lang.IllegalArgumentException: URI has a query component
18:55:48 | at java.io.File.<init>(File.java:427)
18:55:48 | at sbt.IO$.uriToFile(IO.scala:160)
18:55:48 | at sbt.IO$.toFile(IO.scala:135)
18:55:48 | at sbt.Classpaths$.sbt$Classpaths$$bootRepository(Defaults.scala:2028)
18:55:48 | at sbt.Classpaths$$anonfun$appRepositories$1.apply(Defaults.scala:1998)

**Comment by clemensutschig** [comment]
The whole quickstarter needs Engineering- i suggest to store the Template locally to increase Performance and also provide version safety.
